name: New Relic Terraform Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'environments/aws/prive-sit/sit/**'
  pull_request:
    branches:
      - master
    paths:
      - 'environments/aws/prive-sit/sit/**'
  workflow_dispatch:

jobs:
  newrelic-plan:
    uses: anmolkumar-prive/Terraform/.github/workflows/reusable-terraform.yml
    with:
      provider: newrelic
      environment: ${{ github.event.inputs.environment }}
      working_directory: ${{ github.event.inputs.working_directory }}
      terraform_version: '1.9.4' # optional override
      tflint_version: 'v0.60.0'  # optional override
      sops_version: '3.7.3'      # optional override
      plan_approvers: 'team-devops' # optional override
    secrets:
      GITHUB_PAT_TOKEN: ${{ secrets.GITHUB_PAT_TOKEN }}
      PLAN_ENCRYPT: ${{ secrets.PLAN_ENCRYPT }}
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}