name: New Relic Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment name"
        required: true
      working_directory:
        description: "Terraform working directory"
        required: true

jobs:
  newrelic-plan:
    uses: ./.github/workflows/reusable-terraform.yml@main
    with:
      provider: newrelic
      environment: ${{ github.event.inputs.environment }}
      working_directory: ${{ github.event.inputs.working_directory }}
      terraform_version: '1.9.4' # optional override
      tflint_version: 'v0.60.0'  # optional override
      sops_version: '3.7.3'      # optional override
      plan_approvers: 'team-devops' # optional override
    secrets:
      GITHUB_PAT_TOKEN: ${{ secrets.GITHUB_PAT_TOKEN }}
      PLAN_ENCRYPT: ${{ secrets.PLAN_ENCRYPT }}
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}