name: New Relic Terraform Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**'                # Trigger on any file change
  pull_request:
    branches:
      - main
    paths:
      - '**'                # Trigger on any file change
  workflow_dispatch:         # Also allow manual trigger

jobs:
  newrelic-plan:
    uses: anmolkumar-prive/Terraform/.github/workflows/reusable-terraform.yml@main

    with:
      provider: newrelic
      environment: SIT-SG                 # Hardcoded for testing
      working_directory: .                # Root folder
      terraform_version: '1.9.4'
      tflint_version: 'v0.60.0'
      sops_version: '3.7.3'
      plan_approvers: 'team-devops'

    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PLAN_ENCRYPT: ${{ secrets.PLAN_ENCRYPT }}
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}